fix: tuples type generation support (#1011)
drwpow/openapi-typescript pull request #1082
Opened 2023-04-23 07:39 UTC by liangskyli

## Changes

fix bug: #1011

2023-04-24 15:57 UTC, drwpow commented on test/schema-object.test.ts
> +        const schema: SchemaObject = { type: "array", items: [{ type: "string" },{"type": "number"}],minItems:2,maxItems:2 };
```suggestion
        const schema: SchemaObject = { type: "array", prefixItems: [{ type: "string" },{"type": "number"}],minItems:2,maxItems:2 };
```

2023-04-24 15:58 UTC, drwpow requested changes
Thank you very much for the PR! I’m in favor of merging this, but would like this to require usage of `prefixItems` [according to the spec](https://json-schema.org/understanding-json-schema/reference/array.html#tuple-validation) rather than `items`

2023-04-24 23:12 UTC, liangskyli commented
@drwpow : You can add support for prefixItems, but I think items also need support！
see: https://json-schema.org/draft/2020-12/release-notes.html
<img width="800" alt="image" src="https://user-images.githubusercontent.com/31531283/234135086-ec6017a7-0599-430b-bea8-b08a7d1c094f.png">
because: Draft 2019-09 use items, so we alse need support items!

2023-04-24 23:15 UTC, liangskyli commented
@drwpow :You can also look at this！

https://json-schema.org/understanding-json-schema/reference/array.html#tuple-validation
<img width="863" alt="image" src="https://user-images.githubusercontent.com/31531283/234135366-f76742d3-cbac-49ea-99d9-d36eac0f96fa.png">
In Draft 4 - 2019-09, tuple validation was handled by an alternate form of the items keyword. When items was an array of schemas instead of a single schema, it behaved the way prefixItems behaves.

2023-04-25 15:19 UTC, drwpow approved these changes
Thank you for correcting me! I had only used `prefixItems` before for the tuple type, not items. Glad to see `items` supports it too. This all looks good to merge, then!

2023-04-25 15:19 UTC, merged