NextJs options added to fetch
drwpow/openapi-typescript pull request #1571
Opened 2024-02-28 16:07 UTC by petercsaki

## Changes
NextJs uses fetch's options to pass information about caching. These were removed by openapi-fetch.

https://github.com/drwpow/openapi-typescript/issues/1569#issuecomment-1966999115

## Checklist

- [x] Unit tests updated
- [x] `docs/` updated (if necessary)
- [x] `pnpm run update:examples` run (only applicable for openapi-typescript)

2024-02-28 16:18 UTC, drwpow commented
Thank you for opening! I’m +1 in favor of fixing this issue, and the test is perfect! But I would like to solve this **without having any Next.js-specific code in the runtime**. This probably means somehow sniffing out [RequestInit](https://developer.mozilla.org/en-US/docs/Web/API/Request/Request#options) and passing it along before/after each middleware.

If we can make that test pass in a generic way without looking for `.next`, then we’ll not only solve for Next.js; we’ll solve for all other libraries that are experiencing the same issue.

2024-03-05 16:34 UTC, drwpow requested changes
+1 in favor of this merging, and this is a great fix! But as we discussed I’d **like to solve this without manually declaring `.next`.** Perhaps there’s a more universal way we can solve this (such as manually rebuilding `new Request()`s, or another creative solution)?

If we had to have framework-specific code in `openapi-fetch`, we’d always be playing catchup. There’d always be a new vendor prefix (or existing ones could change) and there’d always be something left out and another version to ship. But solving for **any arbitrary property added to the request** would let us solve this problem once and for all.

2024-03-05 16:46 UTC, petercsaki commented
Yep, I get it. I'll need to think about how to get the parameters that aren't used in creating the Request object and should be passed as the second parameter for fetch.

2024-03-06 07:03 UTC, JE-lee commented
After checking the document of the fetch in Next.js and MDN, maybe there is no need to add an external option to achieve that.
We can just add the Next.js options  like this 
```typescript
  const res = await client.GET("/api", { next: {revalidate: 10}})
```
I haven't tested it yet. Have you tried this @petercsaki

2024-03-06 08:39 UTC, petercsaki commented
Yes. Openapi-fetch uses them as parameters when creating the Request object:

https://github.com/drwpow/openapi-typescript/blob/9c277fb0a10c3513de46765a4381ccb722a72af4/packages/openapi-fetch/src/index.js#L72C5-L75C7

but the request object only uses the properties of it that it knows about and others are "forgotten". The code uses only the Request object from then on.

2024-03-06 11:37 UTC, JE-lee commented
> Yes. Openapi-fetch uses them as parameters when creating the Request object:
> 
> https://github.com/drwpow/openapi-typescript/blob/9c277fb0a10c3513de46765a4381ccb722a72af4/packages/openapi-fetch/src/index.js#L72C5-L75C7
> 
> but the request object only uses the properties of it that it knows about and others are "forgotten". The code uses only the Request object from then on. So any custom properties are ignored.

Haha, I got what you mean. I have tested some cases. It seems like The Next.js extended Fetch api only takes the second parameter as the cache option.
The following code works as well as the cache mechanism.

```typescript
  const request = new Request('http://localhost:3000/api/v1/space', {
    method: 'GET',
  })
  const res = await fetch(request, { next: { revalidate: 10 } }) 
```
so you are in the right way. keep going.

2024-03-08 09:49 UTC, IngoVals commented
Would it be possible to switch `NextJsFetchOptions` out for `AdditionalProps` which is defined as an empty object that we spread into the fetch. Then in each case users could ts declare AdditionalProps to what they want ( nextjs props for example ).

```ts
declare module 'openapi-fetch' {
    type AdditionalProps {
        next?: { revalidate?: false | 0 | number; tags?: string[] };
     }
}
```

Just brainstorming.

2024-03-08 15:10 UTC, drwpow commented
@IngoVals love that suggestion! That would be a great addition, and I see the value in typechecking additional properties like that. That would be much better than just adding `[key: string]: unknown` to the shape.

That could either be part of this PR at the author’s discretion, or as a followup.

2024-03-19 15:01 UTC, ryami333 commented
Is this even necessary? Because NextJS uses "ambient modules" to mutate `RequestInit`, which `openapi-typescript` already extends for `FetchOptions`.

2024-03-22 11:38 UTC, petercsaki commented
> Is this even necessary? 

Openapi-fetch loses the next specific parameters before it gets to Next's fetch.

2024-04-28 22:56 UTC, FreeAoi commented
How's going this PR?

2024-05-02 08:15 UTC, petercsaki commented
I've abandoned this, sorry. Someone pointed out that you can pass a custom fetch to each request, and that can use next's cahcing. That solution works for us. Creating a generic solution is not in my scope. Feel free to pick this up.

2024-05-02 14:04 UTC, drwpow commented
No worries! I’m going to close this then, but someone else is free to pick this up, provided my restriction up above: the solution should allow for **any arbitrary properties,** not just `.next`

2024-05-02 14:04 UTC, closed without merging