Pr/873 paths enum
drwpow/openapi-typescript pull request #883
Opened 2022-02-22 10:20 UTC by berzi

Adds the `--makePathsEnum` (`-pe`) option to generate an Enum of operation paths.

Closes #873.

2022-03-28 15:00 UTC, drwpow commented
Thank you for the PR! I’m the only maintainer on this repo so reviews happen as soon as I’m able to. I’ve had some personal things keeping me from being able to look at this project for a little while. Will review now.

2022-03-28 15:04 UTC, drwpow commented on src/load.ts
> +    let contents: string;
minor nitpick, but could this be changed back to `""` for now? it makes runtime more predictable if this initialized to a `string` prototype and has access to all of those methods. an empty string is still falsy

2022-03-28 15:05 UTC, drwpow commented on src/load.ts
> +  const isJSON = !(schema instanceof URL); // if this is dynamically-passed-in JSON, we’ll have to change a few things
please revert this; i find this harder to read

2022-03-28 15:06 UTC, drwpow commented on src/load.ts
> +import { request } from "undici";
Remove both these `undici` lines; they’re already imported above

2022-03-28 15:09 UTC, drwpow requested changes
Overall this is looking good! I’m in favor of merging this, but this PR needs tests. I’d be OK with either Node.js tests, CLI tests, or both (ideally both, but one will suffice, preferably CLI as it tests both).

Other than tests, I left a few comments to revert a couple lines that shouldn’t affect anything you wrote.

Once the tests are in I’d be happy to merge

2022-03-28 15:28 UTC, berzi commented
> Thank you for the PR! I’m the only maintainer on this repo so reviews happen as soon as I’m able to. I’ve had some personal things keeping me from being able to look at this project for a little while. Will review now.

That's alright, sorry for the insistence.

I'll work on the tests and other comments soon, thank you.

2022-04-07 15:37 UTC, berzi commented
CLI test added. 👍

2022-04-24 03:29 UTC, drwpow commented on CONTRIBUTING.md
> +# NOTE: on Windows, try running the script on WSL if getting errors
💯

2022-04-24 03:32 UTC, drwpow approved these changes
Great tests! Thank you

2022-04-24 03:32 UTC, merged

2022-04-24 03:55 UTC, drwpow commented
@all-contributors please add @berzi for code, docs, test

2022-04-27 07:05 UTC, berzi commented
@drwpow Now that the PR is merged I have a question: I ran the script using `npx openapi-typescript@latest openapi.yaml -o my/path/etc -pe`, which pulled version 5.2.0, but the paths weren't generated. Do I have to wait until a version bump to access the new feature (in which case, what's the schedule?) or am I doing something wrong?

2022-05-03 13:48 UTC, berzi commented
Update: the above also happens with 5.3.0. Not sure how to proceed. @drwpow